"""
Django settings for api project.

Generated by 'django-admin startproject' using Django 3.1.3.

For more information on this file, see
https://docs.djangoproject.com/en/3.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.1/ref/settings/
"""
from datetime import timedelta
from pathlib import Path
from os import environ

import sentry_sdk
from sentry_sdk.integrations.django import DjangoIntegration
from sentry_sdk.integrations.logging import ignore_logger

# Build paths inside the project like this: BASE_DIR / 'subdir'.
from auth.exceptions import AuthenticationError

BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "&v)-e5rgzutah7rj%f85#&0x+m@@lu%)2!^*fs*q^r^de)pdma"

DEBUG = not environ.get("API_PRODUCTION_MODE", False)

if DEBUG:
    ALLOWED_HOSTS = ["*"]
    CORS_ORIGIN_ALLOW_ALL = True
else:
    ALLOWED_HOSTS = [
        "api.neuralume.com",
    ]
    CORS_ALLOWED_ORIGINS = [
        "https://cloud.neuralume.com",
        "https://admin.nelu.net",
        "https://www.neuralume.com",
        "https://neuralume.com"
    ]


# if DEBUG:
#     REDIS_HOST = "redis://redis:6379"
# else:
#     REDIS_HOST = "rediss://default:lv1c5du43ccbg7d1@neuralume-api-redis-do-user-8366637-0.b.db.ondigitalocean.com:25061"


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "corsheaders",
    "rest_framework",
    "ariadne.contrib.django",
    # "django_celery_beat",
    "lib",
    "auth",
    # "store",
    "api",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "auth.middleware.DebuggingMiddleware"
]

ROOT_URLCONF = "api.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "api.wsgi.application"

# Database
# https://docs.djangoproject.com/en/3.1/ref/settings/#databases

if DEBUG:
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": BASE_DIR / "db.sqlite3",
        }
    }
else:
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.postgresql_psycopg2",
            "NAME": "defaultdb",
            "USER": "doadmin",
            "PASSWORD": "mxjhyxcey3bkcohn",
            "HOST": "db-postgresql-lon1-83928-do-user-8366637-0.b.db.ondigitalocean.com",
            "PORT": "25060",
        }
    }


# Password validation
# https://docs.djangoproject.com/en/3.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]

AUTH_USER_MODEL = "api.User"

AUTHENTICATION_BACKENDS = [
    "django.contrib.auth.backends.ModelBackend",
    "auth.backends.DjangoJWTBackend",
]

# Internationalization
# https://docs.djangoproject.com/en/3.1/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_L10N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.1/howto/static-files/

STATIC_URL = "/static/"

STATIC_ROOT = "./static/"

# CACHES = {
#     "default": {
#         "BACKEND": "django_redis.cache.RedisCache",
#         "LOCATION": f"{REDIS_HOST}/0",
#         "OPTIONS": {
#             "CLIENT_CLASS": "django_redis.client.DefaultClient",
#         },
#         "PREFIX": "default",
#         "TIMEOUT": None,
#     },
#     "measurements": {
#         "BACKEND": "django_redis.cache.RedisCache",
#         "LOCATION": f"{REDIS_HOST}/1",
#         "OPTIONS": {
#             "CLIENT_CLASS": "django_redis.client.DefaultClient",
#         },
#         "PREFIX": "measurements",
#         "TIMEOUT": None,
#     },
# }


REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": [
        # "rest_framework.authentication.SessionAuthentication",
        # "rest_framework.authentication.BasicAuthentication",
        "auth.backends.DRFBoardTokenAuthentication",
    ]
}

# CELERY_BROKER_URL = f"{REDIS_HOST}/2"
# CELERY_RESULT_BACKEND = f"{REDIS_HOST}/2"


REST_KNOX = {
    "TOKEN_TTL": None,
    "AUTO_REFRESH": False,
}

APPEND_SLASH = False


MEASUREMENTS_PERSIST_FREQUENCY = timedelta(minutes=5)

# CELERY_BEAT_SCHEDULER = "django_celery_beat.schedulers:DatabaseScheduler"
# CELERY_BEAT_SCHEDULE = {
#     "persist_cached_measurements": {
#         "task": "api.tasks.persist_cached_measurements",
#         "schedule": MEASUREMENTS_PERSIST_FREQUENCY,
#         "args": [],
#     },
# }

AUTH_JWT_REFRESH_TOKEN_N_BYTES = 20
AUTH_JWT_REFRESH_EXPIRATION_DELTA = timedelta(days=365)
AUTH_JWT_EXPIRATION_DELTA = timedelta(minutes=5)

if not DEBUG:
    sentry_sdk.init(
        dsn="https://dccb23bb8bfb440fa465e8e610419949@o504581.ingest.sentry.io/5591666",
        integrations=[DjangoIntegration()],
        traces_sample_rate=1.0,
        ignore_errors=[AuthenticationError],

        # If you wish to associate users to errors (assuming you are using
        # django.contrib.auth) you may enable sending PII data.
        send_default_pii=True,
        server_name='api.neuralume.com',
        request_bodies='always',
        with_locals=True,
    )
ignore_logger("django.security.DisallowedHost")

SENDGRID_TEMPLATE_ID = 'd-64a1af877b79447ab9aba3b4e9e25575'
SENDGRID_API_KEY = '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'

if DEBUG:
    STRIPE_API_KEY = 'sk_test_51IB6UdJbXjVSLCa4vJtjKyRc9VrCTzG8yDzI5WHG5cuU36pj3c7MMPZkFp59LOstLITE9H6An5OUE9Byl8ovyP2t00eTXyI9ti'
    PREORDER_SUCCESS_URL = 'http://localhost:3000/nebula/preorder/completed?session_id={CHECKOUT_SESSION_ID}'
    PREORDER_CANCEL_URL = 'http://localhost:3000/nebula/preorder/cancelled'
    STRIPE_NEBULA_PRICE = {
        'default': 'price_1IgGlmJbXjVSLCa4PHuhn1Tr',
        '1': 'price_1IgIaKJbXjVSLCa4eddfqijc',
        '2-4': 'price_1IgIaiJbXjVSLCa4n3VmOouT',
        '5-9': 'price_1IgIb4JbXjVSLCa47EnHweS3',
        '10-19': 'price_1IgIcSJbXjVSLCa4rZopVoQc',
        '20-49': 'price_1IgIciJbXjVSLCa4uGuN5j0b',
        '50-99': 'price_1IgIdCJbXjVSLCa4MNRHKMXg',
        '100-499': 'price_1IgIdaJbXjVSLCa4H34T8zm7',
        '>=500': 'price_1IgIdtJbXjVSLCa4RqdEuATd',
    }
    STRIPE_TAX_RATE_ID = 'txr_1IgeDLJbXjVSLCa4hiLKpJHi'

else:
    STRIPE_API_KEY = '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'
    PREORDER_SUCCESS_URL = 'https://neuralume.com/nebula/preorder/completed?session_id={CHECKOUT_SESSION_ID}'
    PREORDER_CANCEL_URL = 'https://neuralume.com/nebula/preorder/cancelled'
    STRIPE_NEBULA_PRICE = {
        'default': 'price_1IgrS5JbXjVSLCa4jthyL9ey',
        '1': 'price_1IgrS5JbXjVSLCa4MTYNEPKp',
        '2-4': 'price_1IgrS5JbXjVSLCa4XNtghdeH',
        '5-9': 'price_1IgrS5JbXjVSLCa4p6Ge5hQZ',
        '10-19': 'price_1IgrS5JbXjVSLCa4hBfe065q',
        '20-49': 'price_1IgrS5JbXjVSLCa417HWns5V',
        '50-99': 'price_1IgrS5JbXjVSLCa48EF932dL',
        '100-499': 'price_1IgrS5JbXjVSLCa4KX7gLkD3',
        '>=500': 'price_1IgrS5JbXjVSLCa4yUwzNQE1',
    }
    STRIPE_TAX_RATE_ID = 'txr_1IgrVJJbXjVSLCa4B91igXpt'
